services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maniacos_laravel_app
    ports:
      - "8081:80"
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: maniacos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network
    ports:
      - "5432:5432"

networks:
  laravel_network:
    driver: bridge

volumes:
  postgres_data: